"""Reproducible analyses that turn oracle outputs into model design choices."""

from blackjack.analysis.bet_tokens import (
    SELECTED_BET_VOCABULARY,
    BetAction,
    BetToken,
    BetVocabulary,
    EmpiricalReturnDistribution,
    EmpiricalReturnOutcome,
    PilotConfiguration,
    PilotMetrics,
    PilotObservation,
    SampledComposition,
    analyze_vocabulary,
    candidate_vocabularies,
    empirical_round_return_distribution,
    run_bet_token_pilot,
    sample_representative_compositions,
)
from blackjack.analysis.play_sampling import (
    ExactPlayState,
    PlayRolloutConfiguration,
    PlayRolloutMetrics,
    PlayRolloutValidation,
    PlaySamplingConfiguration,
    PlaySamplingMetrics,
    PlaySamplingValidation,
    exact_play_sampling_corpus,
    run_play_rollout_validation,
    run_play_sampling_validation,
)

__all__ = [
    "SELECTED_BET_VOCABULARY",
    "BetAction",
    "BetToken",
    "BetVocabulary",
    "EmpiricalReturnDistribution",
    "EmpiricalReturnOutcome",
    "ExactPlayState",
    "PilotConfiguration",
    "PilotMetrics",
    "PilotObservation",
    "PlayRolloutConfiguration",
    "PlayRolloutMetrics",
    "PlayRolloutValidation",
    "PlaySamplingConfiguration",
    "PlaySamplingMetrics",
    "PlaySamplingValidation",
    "SampledComposition",
    "analyze_vocabulary",
    "candidate_vocabularies",
    "empirical_round_return_distribution",
    "exact_play_sampling_corpus",
    "run_bet_token_pilot",
    "run_play_rollout_validation",
    "run_play_sampling_validation",
    "sample_representative_compositions",
]
